version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing node modules
      - npm install
  build:
    commands:
      - echo Running tests
      - npm run test
